Repository redis/hiredis-py, pull requests merged in 2024-07, with the labels that each got.

#181 Removing python 3.7 trove
  .github/workflows/integration.yaml
  README.md
  dev_requirements.txt
  setup.py
Labels: maintenance

#190 Fix building the wheel for windows
  .github/workflows/REUSABLE-wheeler.yaml
  .gitignore
Labels: maintenance

#192 Fix small mistake
  README.md
Labels: maintenance

#193 Version 2.4.0
  hiredis/version.py
Labels: skip-changelog

#189 Return Redis sets as Python lists
  hiredis/version.py
  src/reader.c
  tests/test_reader.py
Labels: breakingchange, bug
